name: Python CDK
description: Executes a CDK command on a Python project
author: JarradPosey(jarrad.posey@ausnetservices.com.au)
inputs:
  cdk_subcommand:
    required: true
    description: 'AWS CDK subcommand to execute.'
  cdk_stack:
    required: false
    description: 'AWS CDK stack name to execute.'
    default: '*'
  cdk_args:
    required: false
    description: 'AWS CDK subcommand arguments.'
  working_dir:
    required: false
    description: 'AWS CDK working directory.'
    default: '.'
  requirements_file:
    required: false
    description: 'Relative path to python requirements file from working_dir'
    default: 'requirements.txt'
  actions_comment:
    required: false
    description: 'Whether or not to comment on pull requests.'
    default: 'true'
outputs:
  status_code:
    description: 'Returned status code.'
runs:
  using: docker
  image: Dockerfile